"""MQL5 Expert Advisor Generator.

Generates production-ready MQL5 EA code from strategy configuration.
"""

from typing import Any
from jinja2 import Template


MQL5_TEMPLATE = '''//+------------------------------------------------------------------+
//|                                              {{ strategy_name }}.mq5 |
//|                         Generated by Cybabot Ultra                   |
//|                    ForexPrecision RoboQuant Platform                 |
//+------------------------------------------------------------------+
#property copyright "Generated by Cybabot Ultra"
#property link      "https://cybabot.ai"
#property version   "1.00"
#property strict

//--- Input Parameters
input group "=== Strategy Settings ==="
input string   InpStrategyName    = "{{ strategy_name }}";
input string   InpSymbol          = "{{ symbol }}";
input ENUM_TIMEFRAMES InpTimeframe = {{ timeframe }};

input group "=== Entry Parameters ==="
{% for param in entry_params %}
input {{ param.type }} {{ param.name }} = {{ param.default }};  // {{ param.description }}
{% endfor %}

input group "=== Risk Management ==="
input double   InpRiskPercent     = {{ risk_percent }};    // Risk per trade (%)
input double   InpStopLossPips    = {{ stop_loss_pips }};  // Stop loss in pips
input double   InpTakeProfitPips  = {{ take_profit_pips }}; // Take profit in pips
input int      InpMaxTrades       = {{ max_trades }};      // Maximum concurrent trades
input bool     InpUseTrailingStop = {{ use_trailing }};    // Use trailing stop
input double   InpTrailingPips    = {{ trailing_pips }};   // Trailing stop distance

input group "=== Session Filter ==="
input bool     InpUseLondon       = {{ use_london }};      // Trade London session
input bool     InpUseNewYork      = {{ use_newyork }};     // Trade New York session
input bool     InpUseAsia         = {{ use_asia }};        // Trade Asian session

//--- Global Variables
int    g_magicNumber = {{ magic_number }};
double g_pipValue;
int    g_digits;

{% for indicator in indicators %}
int    g_{{ indicator.handle_name }};
{% endfor %}

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit()
{
   // Validate symbol
   if(Symbol() != InpSymbol && InpSymbol != "")
   {
      Print("Warning: Running on ", Symbol(), " but configured for ", InpSymbol);
   }
   
   // Get pip value
   g_digits = (int)SymbolInfoInteger(Symbol(), SYMBOL_DIGITS);
   g_pipValue = (g_digits == 3 || g_digits == 5) ? 0.0001 : 0.01;
   
   // Initialize indicators
{% for indicator in indicators %}
   g_{{ indicator.handle_name }} = {{ indicator.init_call }};
   if(g_{{ indicator.handle_name }} == INVALID_HANDLE)
   {
      Print("Failed to create {{ indicator.name }} indicator");
      return INIT_FAILED;
   }
{% endfor %}
   
   Print("{{ strategy_name }} EA initialized successfully");
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
{% for indicator in indicators %}
   if(g_{{ indicator.handle_name }} != INVALID_HANDLE)
      IndicatorRelease(g_{{ indicator.handle_name }});
{% endfor %}
}

//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check for new bar
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(Symbol(), InpTimeframe, 0);
   if(currentBarTime == lastBarTime) return;
   lastBarTime = currentBarTime;
   
   // Session filter
   if(!IsSessionActive()) return;
   
   // Check max trades
   if(CountOpenTrades() >= InpMaxTrades) return;
   
   // Get indicator values
{% for indicator in indicators %}
   double {{ indicator.buffer_name }}[];
   ArraySetAsSeries({{ indicator.buffer_name }}, true);
   if(CopyBuffer(g_{{ indicator.handle_name }}, 0, 0, 3, {{ indicator.buffer_name }}) < 3) return;
{% endfor %}
   
   // Check entry conditions
   bool longSignal = CheckLongEntry({{ indicator_args }});
   bool shortSignal = CheckShortEntry({{ indicator_args }});
   
   // Execute trades
   if(longSignal && !HasOpenTrade(POSITION_TYPE_BUY))
      OpenTrade(ORDER_TYPE_BUY);
   
   if(shortSignal && !HasOpenTrade(POSITION_TYPE_SELL))
      OpenTrade(ORDER_TYPE_SELL);
   
   // Manage open trades
   ManageOpenTrades();
}

//+------------------------------------------------------------------+
//| Check long entry conditions                                        |
//+------------------------------------------------------------------+
bool CheckLongEntry({{ indicator_params }})
{
   // {{ long_entry_description }}
{{ long_entry_code }}
}

//+------------------------------------------------------------------+
//| Check short entry conditions                                       |
//+------------------------------------------------------------------+
bool CheckShortEntry({{ indicator_params }})
{
   // {{ short_entry_description }}
{{ short_entry_code }}
}

//+------------------------------------------------------------------+
//| Open a trade                                                       |
//+------------------------------------------------------------------+
void OpenTrade(ENUM_ORDER_TYPE orderType)
{
   double price = (orderType == ORDER_TYPE_BUY) ? 
                  SymbolInfoDouble(Symbol(), SYMBOL_ASK) : 
                  SymbolInfoDouble(Symbol(), SYMBOL_BID);
   
   double slPips = InpStopLossPips * g_pipValue;
   double tpPips = InpTakeProfitPips * g_pipValue;
   
   double sl = (orderType == ORDER_TYPE_BUY) ? price - slPips : price + slPips;
   double tp = (orderType == ORDER_TYPE_BUY) ? price + tpPips : price - tpPips;
   
   // Calculate lot size based on risk
   double lotSize = CalculateLotSize(InpStopLossPips);
   
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   
   request.action   = TRADE_ACTION_DEAL;
   request.symbol   = Symbol();
   request.volume   = lotSize;
   request.type     = orderType;
   request.price    = price;
   request.sl       = sl;
   request.tp       = tp;
   request.magic    = g_magicNumber;
   request.comment  = "{{ strategy_name }}";
   request.deviation = 10;
   
   if(!OrderSend(request, result))
      Print("OrderSend failed: ", GetLastError());
   else
      Print("Trade opened: ", result.order);
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                        |
//+------------------------------------------------------------------+
double CalculateLotSize(double stopLossPips)
{
   double accountBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = accountBalance * InpRiskPercent / 100.0;
   
   double tickValue = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_SIZE);
   double pipValuePerLot = (g_pipValue / tickSize) * tickValue;
   
   double lotSize = riskAmount / (stopLossPips * pipValuePerLot);
   
   double minLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP);
   
   lotSize = MathMax(minLot, MathMin(maxLot, MathRound(lotSize / lotStep) * lotStep));
   
   return lotSize;
}

//+------------------------------------------------------------------+
//| Manage open trades (trailing stop, etc.)                          |
//+------------------------------------------------------------------+
void ManageOpenTrades()
{
   if(!InpUseTrailingStop) return;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) != Symbol()) continue;
      if(PositionGetInteger(POSITION_MAGIC) != g_magicNumber) continue;
      
      double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double trailingDist = InpTrailingPips * g_pipValue;
      
      ENUM_POSITION_TYPE posType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      
      if(posType == POSITION_TYPE_BUY)
      {
         double newSL = currentPrice - trailingDist;
         if(newSL > currentSL + g_pipValue)
         {
            MqlTradeRequest req = {};
            MqlTradeResult res = {};
            req.action = TRADE_ACTION_SLTP;
            req.position = ticket;
            req.sl = newSL;
            req.tp = PositionGetDouble(POSITION_TP);
            OrderSend(req, res);
         }
      }
      else if(posType == POSITION_TYPE_SELL)
      {
         double newSL = currentPrice + trailingDist;
         if(newSL < currentSL - g_pipValue || currentSL == 0)
         {
            MqlTradeRequest req = {};
            MqlTradeResult res = {};
            req.action = TRADE_ACTION_SLTP;
            req.position = ticket;
            req.sl = newSL;
            req.tp = PositionGetDouble(POSITION_TP);
            OrderSend(req, res);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Check if session is active                                         |
//+------------------------------------------------------------------+
bool IsSessionActive()
{
   if(!InpUseLondon && !InpUseNewYork && !InpUseAsia) return true;
   
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   int hour = dt.hour;
   
   // London: 08:00-17:00 UTC
   if(InpUseLondon && hour >= 8 && hour < 17) return true;
   
   // New York: 13:00-22:00 UTC
   if(InpUseNewYork && hour >= 13 && hour < 22) return true;
   
   // Asia: 00:00-09:00 UTC
   if(InpUseAsia && (hour >= 0 && hour < 9)) return true;
   
   return false;
}

//+------------------------------------------------------------------+
//| Count open trades for this EA                                      |
//+------------------------------------------------------------------+
int CountOpenTrades()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetTicket(i) > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == Symbol() &&
            PositionGetInteger(POSITION_MAGIC) == g_magicNumber)
            count++;
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Check if there's an open trade of specified type                   |
//+------------------------------------------------------------------+
bool HasOpenTrade(ENUM_POSITION_TYPE posType)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetTicket(i) > 0)
      {
         if(PositionGetString(POSITION_SYMBOL) == Symbol() &&
            PositionGetInteger(POSITION_MAGIC) == g_magicNumber &&
            (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == posType)
            return true;
      }
   }
   return false;
}
//+------------------------------------------------------------------+
'''


def generate_mql5_ea(strategy_config: dict[str, Any]) -> str:
    """Generate MQL5 Expert Advisor code from strategy configuration."""
    template = Template(MQL5_TEMPLATE)

    # Extract strategy parameters
    name = strategy_config.get("name", "CybabotStrategy")
    symbol = strategy_config.get("currency_pairs", ["EURUSD"])[0]
    timeframe = _convert_timeframe(strategy_config.get("timeframes", ["H1"])[0])
    risk = strategy_config.get("risk_parameters", {})
    entry = strategy_config.get("entry_rules", {})
    indicators = strategy_config.get("indicators", [])

    # Build indicator list
    mql5_indicators = _build_indicators(indicators)

    # Build entry code
    long_code, short_code = _build_entry_code(entry, indicators)

    # Build entry parameters
    entry_params = _build_entry_params(strategy_config)

    code = template.render(
        strategy_name=name.replace(" ", "_"),
        symbol=symbol,
        timeframe=timeframe,
        entry_params=entry_params,
        risk_percent=risk.get("risk_per_trade_pct", 2.0),
        stop_loss_pips=risk.get("stop_loss_pips", 20),
        take_profit_pips=risk.get("take_profit_pips", 40),
        max_trades=risk.get("max_concurrent_trades", 3),
        use_trailing=str(risk.get("use_trailing_stop", False)).lower(),
        trailing_pips=risk.get("trailing_stop_pips", 15),
        use_london=str(strategy_config.get("session_filter", {}).get("london", True)).lower(),
        use_newyork=str(strategy_config.get("session_filter", {}).get("new_york", True)).lower(),
        use_asia=str(strategy_config.get("session_filter", {}).get("asia", False)).lower(),
        magic_number=12345,
        indicators=mql5_indicators,
        indicator_args=", ".join([f"{ind['buffer_name']}[]" for ind in mql5_indicators]),
        indicator_params=", ".join([f"const double &{ind['buffer_name']}[]" for ind in mql5_indicators]),
        long_entry_description=entry.get("long_description", "Long entry conditions"),
        short_entry_description=entry.get("short_description", "Short entry conditions"),
        long_entry_code=long_code,
        short_entry_code=short_code,
    )

    return code


def _convert_timeframe(tf: str) -> str:
    """Convert timeframe string to MQL5 constant."""
    mapping = {
        "M1": "PERIOD_M1",
        "M5": "PERIOD_M5",
        "M15": "PERIOD_M15",
        "M30": "PERIOD_M30",
        "H1": "PERIOD_H1",
        "H4": "PERIOD_H4",
        "D1": "PERIOD_D1",
        "W1": "PERIOD_W1",
    }
    return mapping.get(tf.upper(), "PERIOD_H1")


def _build_indicators(indicators: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build MQL5 indicator initialization code."""
    mql5_indicators = []
    for ind in indicators:
        name = ind.get("name", "").upper()
        params = ind.get("parameters", {})

        if "MA" in name or "EMA" in name or "SMA" in name:
            period = params.get("period", 20)
            handle_name = f"handle_{name.lower()}_{period}"
            buffer_name = f"buf_{name.lower()}_{period}"
            init_call = f"iMA(Symbol(), InpTimeframe, {period}, 0, MODE_EMA, PRICE_CLOSE)"
        elif "RSI" in name:
            period = params.get("period", 14)
            handle_name = f"handle_rsi_{period}"
            buffer_name = f"buf_rsi_{period}"
            init_call = f"iRSI(Symbol(), InpTimeframe, {period}, PRICE_CLOSE)"
        elif "MACD" in name:
            fast = params.get("fast_period", 12)
            slow = params.get("slow_period", 26)
            signal = params.get("signal_period", 9)
            handle_name = "handle_macd"
            buffer_name = "buf_macd"
            init_call = f"iMACD(Symbol(), InpTimeframe, {fast}, {slow}, {signal}, PRICE_CLOSE)"
        elif "ATR" in name:
            period = params.get("period", 14)
            handle_name = f"handle_atr_{period}"
            buffer_name = f"buf_atr_{period}"
            init_call = f"iATR(Symbol(), InpTimeframe, {period})"
        elif "BOLLINGER" in name or "BB" in name:
            period = params.get("period", 20)
            deviation = params.get("deviation", 2.0)
            handle_name = "handle_bb"
            buffer_name = "buf_bb_upper"
            init_call = f"iBands(Symbol(), InpTimeframe, {period}, 0, {deviation}, PRICE_CLOSE)"
        elif "STOCH" in name:
            k = params.get("k_period", 14)
            d = params.get("d_period", 3)
            handle_name = "handle_stoch"
            buffer_name = "buf_stoch"
            init_call = f"iStochastic(Symbol(), InpTimeframe, {k}, {d}, 3, MODE_SMA, STO_LOWHIGH)"
        else:
            # Generic indicator
            handle_name = f"handle_{name.lower().replace(' ', '_')}"
            buffer_name = f"buf_{name.lower().replace(' ', '_')}"
            init_call = f"iCustom(Symbol(), InpTimeframe, \"{name}\")"

        mql5_indicators.append({
            "name": name,
            "handle_name": handle_name,
            "buffer_name": buffer_name,
            "init_call": init_call,
        })

    return mql5_indicators


def _build_entry_code(entry: dict[str, Any], indicators: list[dict[str, Any]]) -> tuple[str, str]:
    """Build entry condition code."""
    long_conditions = entry.get("long_conditions", [])
    short_conditions = entry.get("short_conditions", [])

    if not long_conditions:
        long_code = "   // Add your long entry conditions here\n   return false;"
    else:
        conditions = "\n   && ".join([f"// {c}" for c in long_conditions])
        long_code = f"   return (\n   {conditions}\n   );"

    if not short_conditions:
        short_code = "   // Add your short entry conditions here\n   return false;"
    else:
        conditions = "\n   && ".join([f"// {c}" for c in short_conditions])
        short_code = f"   return (\n   {conditions}\n   );"

    return long_code, short_code


def _build_entry_params(strategy_config: dict[str, Any]) -> list[dict[str, Any]]:
    """Build input parameter list."""
    params = []
    indicators = strategy_config.get("indicators", [])

    for ind in indicators:
        name = ind.get("name", "")
        for param_name, param_value in ind.get("parameters", {}).items():
            params.append({
                "type": "int" if isinstance(param_value, int) else "double",
                "name": f"Inp{name.replace(' ', '')}{param_name.title()}",
                "default": param_value,
                "description": f"{name} {param_name}",
            })

    return params
