"""Python trading strategy class generator.

Generates a standalone Python class implementing the strategy logic,
compatible with popular backtesting frameworks and live execution.
"""

from typing import Any

PYTHON_CLASS_TEMPLATE = '''"""
{class_name} - Auto-generated by Cybabot Ultra
Generated: {generated_at}

A complete Python trading strategy implementation.
Compatible with custom backtesting frameworks and live execution.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Any


class Direction(Enum):
    """Trade direction."""
    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


@dataclass
class Signal:
    """Trading signal."""
    direction: Direction = Direction.FLAT
    strength: float = 0.0  # 0-100
    stop_loss: float = 0.0
    take_profit: float = 0.0
    lot_size: float = 0.01
    reason: str = ""


@dataclass
class Bar:
    """OHLCV bar data."""
    timestamp: str = ""
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: float = 0.0


class {class_name}:
    """
    {description}
    
    Symbol: {symbol}
    Timeframe: {timeframe}
    
    Indicators:
{indicator_docs}
    
    Entry Logic:
{entry_docs}
    
    Exit Logic:
{exit_docs}
    """

    def __init__(self, params: dict[str, Any] | None = None) -> None:
        """Initialize strategy with parameters."""
        self.params = params or {{}}
        
        # Strategy parameters
        self.symbol = "{symbol}"
        self.timeframe = "{timeframe}"
        
        # Risk management
        self.risk_per_trade_pct = self.params.get("risk_per_trade_pct", {risk_pct})
        self.stop_loss_pips = self.params.get("stop_loss_pips", {sl_pips})
        self.take_profit_pips = self.params.get("take_profit_pips", {tp_pips})
        self.max_positions = self.params.get("max_positions", {max_positions})
        self.trailing_stop = self.params.get("trailing_stop", {trailing_stop})
        
        # Indicator parameters
{indicator_params}
        
        # Internal state
        self._bars: list[Bar] = []
        self._indicators: dict[str, list[float]] = {{}}
        self._position: Direction = Direction.FLAT
        self._open_positions: list[dict] = []
        self._history_required = {history_required}

    def on_bar(self, bar: Bar) -> Signal | None:
        """Process a new bar and return a signal if conditions are met.
        
        Args:
            bar: New OHLCV bar
            
        Returns:
            Signal if entry/exit conditions met, None otherwise
        """
        self._bars.append(bar)
        
        # Wait for enough history
        if len(self._bars) < self._history_required:
            return None
        
        # Update indicators
        self._calculate_indicators()
        
        # Check session filter
        if not self._is_valid_session(bar):
            return None
        
        # Check exit conditions first
        exit_signal = self._check_exit_conditions(bar)
        if exit_signal:
            return exit_signal
        
        # Check entry conditions
        entry_signal = self._check_entry_conditions(bar)
        if entry_signal:
            return entry_signal
        
        return None

    def _calculate_indicators(self) -> None:
        """Calculate all technical indicators."""
        closes = [b.close for b in self._bars]
        highs = [b.high for b in self._bars]
        lows = [b.low for b in self._bars]
        
{indicator_calculations}

    def _check_entry_conditions(self, bar: Bar) -> Signal | None:
        """Check if entry conditions are met."""
{entry_logic}

    def _check_exit_conditions(self, bar: Bar) -> Signal | None:
        """Check if exit conditions are met."""
{exit_logic}

    def _is_valid_session(self, bar: Bar) -> bool:
        """Check if current time is within valid trading session."""
{session_filter}

    def _calculate_position_size(
        self, 
        balance: float, 
        stop_loss_pips: float,
        pip_value: float = 10.0,
    ) -> float:
        """Calculate position size using fixed percentage risk.
        
        Args:
            balance: Account balance
            stop_loss_pips: Stop loss distance in pips
            pip_value: Value per pip per standard lot
            
        Returns:
            Lot size
        """
        if stop_loss_pips <= 0:
            return 0.01
        
        risk_amount = balance * (self.risk_per_trade_pct / 100)
        lot_size = risk_amount / (stop_loss_pips * pip_value)
        
        # Round to 2 decimal places and enforce minimum
        lot_size = max(round(lot_size, 2), 0.01)
        return lot_size

    # ─── Helper Methods ────────────────────────────────────────────────

    @staticmethod
    def _sma(values: list[float], period: int) -> list[float]:
        """Simple Moving Average."""
        if len(values) < period:
            return [0.0] * len(values)
        result = [0.0] * (period - 1)
        for i in range(period - 1, len(values)):
            result.append(sum(values[i - period + 1 : i + 1]) / period)
        return result

    @staticmethod
    def _ema(values: list[float], period: int) -> list[float]:
        """Exponential Moving Average."""
        if not values:
            return []
        multiplier = 2 / (period + 1)
        result = [values[0]]
        for i in range(1, len(values)):
            ema_val = (values[i] - result[-1]) * multiplier + result[-1]
            result.append(ema_val)
        return result

    @staticmethod
    def _rsi(values: list[float], period: int = 14) -> list[float]:
        """Relative Strength Index."""
        if len(values) < period + 1:
            return [50.0] * len(values)
        
        changes = [values[i] - values[i - 1] for i in range(1, len(values))]
        gains = [max(c, 0) for c in changes]
        losses = [abs(min(c, 0)) for c in changes]
        
        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period
        
        result = [50.0] * period  # Padding
        
        for i in range(period, len(changes)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period
            
            if avg_loss == 0:
                result.append(100.0)
            else:
                rs = avg_gain / avg_loss
                result.append(100 - (100 / (1 + rs)))
        
        return result

    @staticmethod
    def _atr(
        highs: list[float], 
        lows: list[float], 
        closes: list[float], 
        period: int = 14,
    ) -> list[float]:
        """Average True Range."""
        if len(highs) < 2:
            return [0.0] * len(highs)
        
        true_ranges = [highs[0] - lows[0]]
        for i in range(1, len(highs)):
            tr = max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i - 1]),
                abs(lows[i] - closes[i - 1]),
            )
            true_ranges.append(tr)
        
        # Use SMA for ATR
        result = [0.0] * (period - 1)
        atr_val = sum(true_ranges[:period]) / period
        result.append(atr_val)
        
        for i in range(period, len(true_ranges)):
            atr_val = (atr_val * (period - 1) + true_ranges[i]) / period
            result.append(atr_val)
        
        return result

    @staticmethod
    def _bollinger_bands(
        values: list[float], 
        period: int = 20, 
        std_dev: float = 2.0,
    ) -> tuple[list[float], list[float], list[float]]:
        """Bollinger Bands (upper, middle, lower)."""
        import math
        
        middle = {class_name}._sma(values, period)
        upper = []
        lower = []
        
        for i in range(len(values)):
            if i < period - 1:
                upper.append(0.0)
                lower.append(0.0)
            else:
                window = values[i - period + 1 : i + 1]
                mean = sum(window) / len(window)
                variance = sum((x - mean) ** 2 for x in window) / len(window)
                sd = math.sqrt(variance) * std_dev
                upper.append(middle[i] + sd)
                lower.append(middle[i] - sd)
        
        return upper, middle, lower

    @staticmethod  
    def _macd(
        values: list[float],
        fast: int = 12,
        slow: int = 26,
        signal: int = 9,
    ) -> tuple[list[float], list[float], list[float]]:
        """MACD (line, signal, histogram)."""
        ema_fast = {class_name}._ema(values, fast)
        ema_slow = {class_name}._ema(values, slow)
        
        macd_line = [f - s for f, s in zip(ema_fast, ema_slow)]
        signal_line = {class_name}._ema(macd_line, signal)
        histogram = [m - s for m, s in zip(macd_line, signal_line)]
        
        return macd_line, signal_line, histogram

    def get_parameters(self) -> dict[str, Any]:
        """Get current strategy parameters."""
        return {{
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "risk_per_trade_pct": self.risk_per_trade_pct,
            "stop_loss_pips": self.stop_loss_pips,
            "take_profit_pips": self.take_profit_pips,
            "max_positions": self.max_positions,
            "trailing_stop": self.trailing_stop,
{get_params_body}
        }}

    def reset(self) -> None:
        """Reset strategy state."""
        self._bars.clear()
        self._indicators.clear()
        self._position = Direction.FLAT
        self._open_positions.clear()
'''


class PythonClassGenerator:
    """Generates Python trading strategy classes from configuration."""

    def generate(self, config: dict[str, Any]) -> str:
        """Generate a complete Python class from strategy config.

        Args:
            config: Strategy configuration dictionary

        Returns:
            Complete Python source code string
        """
        from datetime import datetime

        class_name = config.get("class_name", "CybabotStrategy")
        description = config.get("description", "Auto-generated trading strategy")
        symbol = config.get("symbol", "EURUSD")
        timeframe = config.get("timeframe", "H1")

        indicators = config.get("indicators", [])
        entry_conditions = config.get("entry_conditions", {})
        exit_conditions = config.get("exit_conditions", {})
        risk_mgmt = config.get("risk_management", {})

        # Build indicator documentation
        indicator_docs = self._build_indicator_docs(indicators)

        # Build entry/exit documentation
        entry_docs = self._build_condition_docs(entry_conditions, "entry")
        exit_docs = self._build_condition_docs(exit_conditions, "exit")

        # Build indicator parameters
        indicator_params = self._build_indicator_params(indicators)

        # Build indicator calculations
        indicator_calculations = self._build_indicator_calculations(indicators)

        # Build entry logic
        entry_logic = self._build_entry_logic(entry_conditions, indicators)

        # Build exit logic
        exit_logic = self._build_exit_logic(exit_conditions)

        # Build session filter
        session_filter = self._build_session_filter(config.get("session_filter"))

        # Build get_params body
        get_params_body = self._build_get_params(indicators)

        # Calculate history required
        history_required = self._calculate_history_required(indicators)

        code = PYTHON_CLASS_TEMPLATE.format(
            class_name=class_name,
            generated_at=datetime.utcnow().isoformat(),
            description=description,
            symbol=symbol,
            timeframe=timeframe,
            indicator_docs=indicator_docs,
            entry_docs=entry_docs,
            exit_docs=exit_docs,
            indicator_params=indicator_params,
            indicator_calculations=indicator_calculations,
            entry_logic=entry_logic,
            exit_logic=exit_logic,
            session_filter=session_filter,
            risk_pct=risk_mgmt.get("risk_per_trade_pct", 2.0),
            sl_pips=risk_mgmt.get("stop_loss_pips", 30.0),
            tp_pips=risk_mgmt.get("take_profit_pips", 60.0),
            max_positions=risk_mgmt.get("max_positions", 1),
            trailing_stop=str(risk_mgmt.get("trailing_stop", False)),
            history_required=history_required,
            get_params_body=get_params_body,
        )

        return code

    def _build_indicator_docs(self, indicators: list[dict]) -> str:
        lines = []
        for ind in indicators:
            name = ind.get("name", "unknown")
            params = ind.get("params", {})
            lines.append(f"        - {name}: {params}")
        return "\n".join(lines) if lines else "        - None configured"

    def _build_condition_docs(
        self, conditions: dict[str, Any], ctype: str
    ) -> str:
        if not conditions:
            return f"        - Default {ctype} conditions"

        lines = []
        for key, value in conditions.items():
            lines.append(f"        - {key}: {value}")
        return "\n".join(lines)

    def _build_indicator_params(self, indicators: list[dict]) -> str:
        lines = []
        for ind in indicators:
            name = ind.get("name", "").lower()
            params = ind.get("params", {})
            for param_name, param_value in params.items():
                var_name = f"{name}_{param_name}"
                lines.append(
                    f'        self.{var_name} = self.params.get("{var_name}", {param_value})'
                )
        return "\n".join(lines) if lines else "        pass  # No indicator parameters"

    def _build_indicator_calculations(self, indicators: list[dict]) -> str:
        lines = []
        for ind in indicators:
            name = ind.get("name", "").lower()
            params = ind.get("params", {})
            period = params.get("period", 14)

            if name in ("sma", "ma"):
                lines.append(
                    f'        self._indicators["{name}"] = self._sma(closes, self.{name}_period)'
                )
            elif name == "ema":
                lines.append(
                    f'        self._indicators["{name}"] = self._ema(closes, self.{name}_period)'
                )
            elif name == "rsi":
                lines.append(
                    f'        self._indicators["{name}"] = self._rsi(closes, self.{name}_period)'
                )
            elif name == "atr":
                lines.append(
                    f'        self._indicators["{name}"] = self._atr(highs, lows, closes, self.{name}_period)'
                )
            elif name in ("bb", "bollinger"):
                lines.append(
                    f'        upper, middle, lower = self._bollinger_bands(closes, self.{name}_period)'
                )
                lines.append(f'        self._indicators["{name}_upper"] = upper')
                lines.append(f'        self._indicators["{name}_middle"] = middle')
                lines.append(f'        self._indicators["{name}_lower"] = lower')
            elif name == "macd":
                fast = params.get("fast_period", 12)
                slow = params.get("slow_period", 26)
                sig = params.get("signal_period", 9)
                lines.append(
                    f'        macd_l, signal_l, hist = self._macd(closes, '
                    f"self.{name}_fast_period, self.{name}_slow_period, self.{name}_signal_period)"
                )
                lines.append(f'        self._indicators["{name}_line"] = macd_l')
                lines.append(f'        self._indicators["{name}_signal"] = signal_l')
                lines.append(f'        self._indicators["{name}_histogram"] = hist')
            else:
                lines.append(
                    f'        # TODO: Implement {name} indicator calculation'
                )

        return "\n".join(lines) if lines else "        pass  # No indicators"

    def _build_entry_logic(
        self, conditions: dict[str, Any], indicators: list[dict]
    ) -> str:
        if not conditions:
            return (
                "        # Default entry: no conditions\n"
                "        return None"
            )

        lines = [
            "        # Check long conditions",
            "        long_conditions = []",
            "        short_conditions = []",
            "",
        ]

        long_conds = conditions.get("long", [])
        short_conds = conditions.get("short", [])

        for cond in long_conds:
            lines.append(f"        # {cond.get('description', 'Condition')}")
            indicator = cond.get("indicator", "").lower()
            operator = cond.get("operator", ">")
            value = cond.get("value", 0)

            if indicator in ("rsi", "sma", "ema", "atr"):
                lines.append(
                    f'        if self._indicators.get("{indicator}") and len(self._indicators["{indicator}"]) > 0:'
                )
                lines.append(
                    f'            long_conditions.append(self._indicators["{indicator}"][-1] {operator} {value})'
                )

        for cond in short_conds:
            lines.append(f"        # {cond.get('description', 'Condition')}")
            indicator = cond.get("indicator", "").lower()
            operator = cond.get("operator", "<")
            value = cond.get("value", 0)

            if indicator in ("rsi", "sma", "ema", "atr"):
                lines.append(
                    f'        if self._indicators.get("{indicator}") and len(self._indicators["{indicator}"]) > 0:'
                )
                lines.append(
                    f'            short_conditions.append(self._indicators["{indicator}"][-1] {operator} {value})'
                )

        lines.extend([
            "",
            "        if long_conditions and all(long_conditions):",
            "            return Signal(",
            "                direction=Direction.LONG,",
            "                strength=75.0,",
            "                stop_loss=bar.close - self.stop_loss_pips * 0.0001,",
            "                take_profit=bar.close + self.take_profit_pips * 0.0001,",
            '                reason="Long entry conditions met",',
            "            )",
            "",
            "        if short_conditions and all(short_conditions):",
            "            return Signal(",
            "                direction=Direction.SHORT,",
            "                strength=75.0,",
            "                stop_loss=bar.close + self.stop_loss_pips * 0.0001,",
            "                take_profit=bar.close - self.take_profit_pips * 0.0001,",
            '                reason="Short entry conditions met",',
            "            )",
            "",
            "        return None",
        ])

        return "\n".join(lines)

    def _build_exit_logic(self, conditions: dict[str, Any]) -> str:
        return (
            "        # Exit logic handled by stop loss and take profit\n"
            "        # Override this method for custom exit conditions\n"
            "        return None"
        )

    def _build_session_filter(
        self, session: dict[str, Any] | None
    ) -> str:
        if not session:
            return "        return True  # No session filter"

        start = session.get("start_hour", 8)
        end = session.get("end_hour", 20)

        return (
            f"        # Trading session: {start}:00 - {end}:00 UTC\n"
            f"        try:\n"
            f"            from datetime import datetime\n"
            f"            dt = datetime.fromisoformat(bar.timestamp)\n"
            f"            return {start} <= dt.hour < {end}\n"
            f"        except (ValueError, AttributeError):\n"
            f"            return True"
        )

    def _build_get_params(self, indicators: list[dict]) -> str:
        lines = []
        for ind in indicators:
            name = ind.get("name", "").lower()
            params = ind.get("params", {})
            for param_name in params:
                var_name = f"{name}_{param_name}"
                lines.append(f'            "{var_name}": self.{var_name},')
        return "\n".join(lines) if lines else '            # No indicator params'

    def _calculate_history_required(self, indicators: list[dict]) -> int:
        max_period = 50  # Default minimum
        for ind in indicators:
            params = ind.get("params", {})
            for key, value in params.items():
                if "period" in key and isinstance(value, (int, float)):
                    max_period = max(max_period, int(value) + 10)
        return max_period
